import { Response } from 'express';
import Vehicle from '../models/Vehicle.js';
import User from '../models/User.js';
import Lead from '../models/Lead.js';
import AuditLog from '../models/AuditLog.js';
import { AuthRequest } from '../middleware/auth.js';

/**
 * @desc    Get marketing dashboard stats
 * @route   GET /api/marketing/stats
 * @access  Private (Marketing)
 */
export const getMarketingStats = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user || req.user.role !== 'marketing') {
      res.status(403).json({ success: false, error: 'Not authorized', code: 'FORBIDDEN' });
      return;
    }

    const userId = req.user._id;

    // Stats for leads generated by this marketing member
    const [totalLeads, newLeads, contactedLeads, closedLeads] = await Promise.all([
      Lead.countDocuments({ generatedBy: userId }),
      Lead.countDocuments({ generatedBy: userId, status: 'new' }),
      Lead.countDocuments({ generatedBy: userId, status: 'contacted' }),
      Lead.countDocuments({ generatedBy: userId, status: 'closed' }),
    ]);

    res.status(200).json({
      success: true,
      data: {
        totalLeads,
        newLeads,
        contactedLeads,
        closedLeads,
      }
    });
  } catch (error) {
    console.error('Get marketing stats error:', error);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

/**
 * @desc    Get audit logs for the marketing specialist
 * @route   GET /api/marketing/audit-logs
 * @access  Private (Marketing)
 */
export const getMarketingAuditLogs = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user || req.user.role !== 'marketing') {
      res.status(403).json({ success: false, error: 'Not authorized', code: 'FORBIDDEN' });
      return;
    }

    const logs = await AuditLog.find({ userId: req.user._id })
      .sort({ createdAt: -1 })
      .limit(20)
      .lean();

    res.status(200).json({
      success: true,
      data: logs
    });
  } catch (error) {
    console.error('Get marketing audit logs error:', error);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

/**
 * @desc    Get leads generated by the marketing member
 * @route   GET /api/marketing/leads
 * @access  Private (Marketing)
 */
export const getGeneratedLeads = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user || req.user.role !== 'marketing') {
      res.status(403).json({ success: false, error: 'Not authorized', code: 'FORBIDDEN' });
      return;
    }

    const { status, page = 1, pageSize = 10 } = req.query;
    const query: any = { generatedBy: req.user._id };

    if (status && status !== 'all') {
      query.status = status;
    }

    const pageNum = Number(page);
    const limit = Number(pageSize);
    const skip = (pageNum - 1) * limit;

    const [items, total] = await Promise.all([
      Lead.find(query)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Lead.countDocuments(query),
    ]);

    res.status(200).json({
      success: true,
      data: {
        items,
        total,
        page: pageNum,
        pageSize: limit,
        hasMore: skip + items.length < total,
      }
    });
  } catch (error) {
    console.error('Get generated leads error:', error);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

/**
 * @desc    Create a lead (Lead Generation)
 * @route   POST /api/marketing/leads
 * @access  Private (Marketing)
 */
export const createLead = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user || req.user.role !== 'marketing') {
      res.status(403).json({ success: false, error: 'Not authorized', code: 'FORBIDDEN' });
      return;
    }

    const { name, email, phone, instituteName, type, notes, isMarketingOnly } = req.body;

    if (!name || !email || !phone) {
      res.status(400).json({ success: false, error: 'Name, email, and phone are required' });
      return;
    }

    const lead = await Lead.create({
      name,
      email,
      phone,
      instituteName,
      type,
      notes,
      generatedBy: req.user._id,
      status: 'new',
      isMarketingOnly: isMarketingOnly === true || isMarketingOnly === 'true'
    });

    res.status(201).json({
      success: true,
      data: lead,
      message: 'Lead generated successfully'
    });
  } catch (error) {
    console.error('Create lead error:', error);
    res.status(500).json({ success: false, error: error instanceof Error ? error.message : 'Server error' });
  }
};